name: Test, Analysis, and Coverage

on:
  workflow_dispatch:

jobs:

  test_analysis_coverage:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t shell .

      - name: Execute unit tests
        run: docker run --rm shell /bin/bash -c "cd /comp0010 && nose2 test"

      - name: Execute code analysis
        run: docker run --rm shell /bin/bash -c "cd /comp0010 && flake8 --exclude system_test"

      - name: Execute test coverage
        run: docker run --rm shell /bin/bash -c "cd /comp0010 && coverage run --branch -m nose2 test && coverage report -m"
